### ISSUE TITLE
Can we support window app?

### ISSUE THREAD

**Issue by Stefan-UIT** [Pisey-Nguon/flutter_native_html_to_pdf#1]
I've tried your package, it worked like magic, especially with our html text to pdf. I believe there is no package out there can do this great work.
Unfortunately, I've just notice that the package is not supported window app. We're building local app for window, please help. 🙏

**Comment by Pisey-Nguon** [comment]
Thank you for your interest in my package. I'm glad to hear that it worked well for you. I'm currently investigating the possibility of supporting Windows app. I'll keep you updated on the progress. Thank you for your patience and understanding.

**Comment by Stefan-UIT** [comment]
@Pisey-Nguon Thank you so much, I am really really appreciate it!! 🙏🙏

**Comment by Stefan-UIT** [comment]
Hi @Pisey-Nguon, do we have any updates on supporting Windows app? not mean to bother you but I really need it now. Or you can teach me how to do it. Many thanks 🙏 !

**Comment by Pisey-Nguon** [comment]
> Hi @Pisey-Nguon, do we have any updates on supporting Windows app? not mean to bother you but I really need it now. Or you can teach me how to do it. Many thanks 🙏 !

I still have more investigate this so I will confirm with you by this day

**Comment by Pisey-Nguon** [comment]
> Hi @Pisey-Nguon, do we have any updates on supporting Windows app? not mean to bother you but I really need it now. Or you can teach me how to do it. Many thanks 🙏 !

Please try with this package [https://pub.dev/packages/htmltopdfwidgets](url) instead as currently i still don't have much time to make it support windows app
